### ISSUE TITLE
parms for script to set settings when launching exe

### ISSUE THREAD

**Issue by Trezore** [sw3103/movemouse#1]
Hello,

Is there a way to set certain settings via a script?

For example, to check boxes for:

**Actions tab**
- (set number) second interval
- Move mouse pointer
- Stealth mode (pointer movement not visible)

**Behavior tab**
- Pause when mouse pointer moved
- Automatically resume after (set number) seconds of inactivity
- Minimise to System Tray
 
Thank you in advance.

**Comment by sw3103** [comment]
Hi,

Sorry for taking so long to reply. I didn't realise I'd have to enable notifications on any issues seeing as I am a coordinator.

In answer to your question - yes, you can manipulate Move Mouse settings from a script. This will involve editing the underlying XML settings file directly, which you can do using PowerShell.

Here is an example that will disable Stealth Mode:

```
$XmlPath = Join-Path $env:APPDATA "Ellanet\Move Mouse\Move Mouse.xml"

if (Test-Path -Path $XmlPath) {
    $XmlDoc = New-Object System.Xml.XmlDocument
    $XmlDoc.Load($XmlPath)
    $XmlDoc.SelectSingleNode("settings/stealth_mode").InnerText = $false
    $XmlDoc.Save($XmlPath)
}
```

All you will need to do is use this code in either a Start/Interval/Stop script with the settings you're looking to manipulate.
