### ISSUE TITLE
app window intermittently opening

### ISSUE THREAD

**Issue by mdinsua** [sw3103/movemouse#10]
This has been going on for a while and am just coming in to see if anyone else may have run into this.

I am running Win7 through a vm on my MacBook Pro and after upgrading to 3.5.0, the app window   intermittently opens. I will minimize it, but it never goes back into the systray after the first opening. I have uninstalled and reinstalled; downloaded a new copy, uninstalled and installed the fresh copy with the same behavior.

Just curious to see what anyone might have on this.

**Comment by sw3103** [comment]
Hi,

Thanks for letting me know.

Does this also happen for the 3.4.1 release?

**Comment by sw3103** [comment]
Version 3.6.0 now available without KryptonWinFormControls UI components.
