### ISSUE TITLE
New feature request: add option to hide tray icon

### ISSUE THREAD

**Issue by tlc76** [sw3103/movemouse#11]
Hi,

Please consider adding the following feature: an option to **Hide the tray icon**.
To ensure a minimal control of the program, this new option should be usable only when **Enable start/pause hotkey** option is ticked.

Thanks

**Comment by sw3103** [comment]
Hi,

If you're able to download the latest version from the Microsoft Store, you will see this option.

**Comment by kangaroo72** [comment]
Can you provide the version without MS-Store please? MS-Store is blocked :-/

**Comment by sw3103** [comment]
At this point in time version 4.x will only be available from the Microsoft Store. I do plan at some point when I get time to make that version open source, although there are a few changes I need to make before I can do that.

**Comment by thunderpants** [comment]
Yep ,been wanting an alternative download link for ages.
Store always has a connection error ,it would take a few seconds to make a simple download link.
god ,some devs are just so weird.

**Comment by saiyzh** [comment]
Can you provide the version without MS-Store please? MS-Store is blocked :-/

**Comment by sw3103** [comment]
https://sites.google.com/a/windandkite.co.uk/movemouse/help/hints#h.p_YowAQ60QR-nn

**Comment by sw3103** [comment]
https://sites.google.com/a/windandkite.co.uk/movemouse/help/hints#h.p_YowAQ60QR-nn
