### ISSUE TITLE
v.4.0 ?

### ISSUE THREAD

**Issue by thunderpants** [sw3103/movemouse#12]
Any chance of having v4.0 on GitHub?

Win10 store won't open for me and probably  other people too who don't have the "full microsoft bloat" installed that comes with some versions of win10.

**Comment by sw3103** [comment]
Hi,

At the moment version 4.x is only available in the Microsoft Store, although I'm ruling out making it open source at some point in the future.

**Comment by thunderpants** [comment]
oh ,so only available in a closed store ,ok.
