### ISSUE TITLE
The Actions' [     ] second interval can be saved or persistence

### ISSUE THREAD

**Issue by caot** [sw3103/movemouse#14]
It's good to keep the Actions' `[     ] second interval` saved or persistence. There might be other fields that can be saved or persistence also. The data can be saved on change other than a save button.

![move_mouse](https://user-images.githubusercontent.com/5083030/79863477-d2574a80-83a5-11ea-8091-4b3d998b5bf1.png)

**Comment by sw3103** [comment]
All settings should be persistent. Is this not the case for you?

**Comment by caot** [comment]
It looks right. Thanks.
