### ISSUE TITLE
Google Drive Detects Move Mouse as Virus

### ISSUE THREAD

**Issue by rrenca** [sw3103/movemouse#16]
![Capture (2)](https://user-images.githubusercontent.com/62807909/85678767-5fe34d80-b6fb-11ea-88aa-2d0c86827041.PNG)
How come Google Drive detects the Exe file as a virus?

**Comment by sw3103** [comment]
I have no idea. Does it not give you any information regarding the "virus"?

**Comment by arrenca** [comment]
https://www.virustotal.com/gui/file/23bb0740455d3be1ab23baac187c225b0743e81b5567fa8ff5757edda24953bf/detection

![image](https://user-images.githubusercontent.com/62807909/86331815-2cb13900-bc7c-11ea-8b91-92671e0911bf.png)

**Comment by sw3103** [comment]
Maybe try version 4.x now available on GitHub.
