### ISSUE TITLE
Uninstalling the program

### ISSUE THREAD

**Issue by JulianHQ** [sw3103/movemouse#17]
Hey, I noticed the program downloaded and installed something on my machine. Now I want to uninstall it but I do not see an option to do so. It doesn't appear in the Programs Installed windows list.

![image](https://user-images.githubusercontent.com/17477562/86983744-4e199580-c152-11ea-88f0-33bcc0e6c9a1.png)
---
![image](https://user-images.githubusercontent.com/17477562/86983771-5d004800-c152-11ea-9f74-9012eb7f0fbf.png)

**Comment by sw3103** [comment]
Where did you get this version from? The 3.x version has always been a standalone application and does not need installing.

**Comment by JulianHQ** [comment]
I got this version from a co-worker.

![image](https://user-images.githubusercontent.com/17477562/87096771-2b968380-c209-11ea-8dc3-42e4af304927.png)

But now I recall having a pop up telling me the application needed some version of the .NET Framework. If that's the case, then that's what it downloaded and installed.

**Comment by sw3103** [comment]
Closing as Move Mouse is a standalone exe.
