### ISSUE TITLE
Release 4.x on Github for users without Windows Store

### ISSUE THREAD

**Issue by ghost** [sw3103/movemouse#18]
Some corporate Windows environments are extremely locked down and do not have access to the Windows Store. These types of machines are the exact target environment for Move Mouse. Providing a .zip download of the 4.x series (like the old 3.x series) for these locked down Windows 10 environments would be a godsend!

**Comment by saiyzh** [comment]
it's 4.x release? i cant find it

**Comment by divisionbyzeroerror** [comment]
@saiyzh from https://github.com/sw3103/movemouse
"Move Mouse 3.x project which was previously hosted on CodePlex. Windows 10 users should head over to the Microsoft Store to download the latest 4.x version."

**Comment by arrenca** [comment]
Yes please thank you very much!

**Comment by brikuth** [comment]
Please release the exe for 4.0 - windows store not available on most corp machines.

**Comment by NightFright2k19** [comment]
You may rather stick to v3.6.0 since apparently 4.x has some features removed, such as hidden mouse movements. 3.x also works just fine on Win10 systems while not requiring installation.

**Comment by sw3103** [comment]
Version 4.x now available on GitHub.
