### ISSUE TITLE
Where is the "send keystroke" action in 4.x? 

### ISSUE THREAD

**Issue by Proaxel** [sw3103/movemouse#2]
In 3.x, there was the ability to have the application mimic pressing a keyboard key on the intervals. I do not see any sort of functionality in the 4.x versions. Where is it?

**Comment by lackoder** [comment]
You can achieve this with a couple of lines of PowerShell code:
https://technet.microsoft.com/en-us/library/ff731008.aspx
Create a script and add it to the list of Move Mouse actions.

**Comment by sw3103** [comment]
This will be something that will soon be made available in 4.x, but the script method above should is a good solution in the meantime.
