### ISSUE TITLE
Windows Defender detects a trojan

### ISSUE THREAD

**Issue by TheUntouchable** [sw3103/movemouse#20]
Hi!

I just found out that there is a new version of your program, used the 3.6 version till now.

But when i tried to open the zip archive, my Windows Defender kicks in end tells me it found some trojan thing..

![grafik](https://user-images.githubusercontent.com/2162540/155596521-3fbf0ed3-7808-4532-9b2a-80dd260c6180.png)

VirusTotal has only one finding, so I think its a false positiv:
https://www.virustotal.com/gui/file/57ad21a630fd4b1a4970344236ee705ffe8cba7e63a0e4be1276979f24323204

Can you say something regarding that? :)

**Comment by sw3103** [comment]
Some virus scanners have been known in the past to see Move Mouse activity to be virus-like. Unfortunately there's not much I can do about that.

This is the same version that I publish to the Microsoft Store, which undergoes various tests during the publishing process to ensure it is safe. The source code is also now published here for all to see that there is nothing malicious in the code.

**Comment by TheUntouchable** [comment]
Thanks for the clarification! :)
