### ISSUE TITLE
[Feature Request] - pause when on battery

### ISSUE THREAD

**Issue by tomiko23lol** [sw3103/movemouse#24]
Hello, I would like to  **request feature** ( option) to be added to MouseMove.

I would like to have option to dissable / pause MoveMouse app or actions when running on battery, to allow my screen go to sleep when running from battery and automatically start actions again when laptop is connected to charger.

Thank You.

**Comment by sw3103** [comment]
That's been on my list for a while, but good to track it here also.

**Comment by sw3103** [comment]
https://github.com/sw3103/movemouse/releases/tag/v4.15.0
