### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by EQNish** [sw3103/movemouse#26]
On the Interval Option have a count of intervals ie, many many times in should run that step where 0 == infinite, up tp XXXX times

**Comment by schorbitz** [comment]
Second this.
For example with a move mouse action on repeat every 4 minutes, set to stop after 10 iterations. The screensaver still works but with timeout of ~45 minutes instead of the enforced 5 minutes.

**Comment by sw3103** [comment]
I have just released 4.16.0 that includes this feature. Please test and let me know your feedback.

![image](https://user-images.githubusercontent.com/29467423/214961891-cf34ed4f-57c0-4176-9f3e-8c44079510dc.png)
![image](https://user-images.githubusercontent.com/29467423/214961980-9c18936d-0bd7-4393-9c33-002677464abf.png)

https://github.com/sw3103/movemouse/releases/tag/v4.16.0
