### ISSUE TITLE
[Feature Request] Keep Citrix Workspace Session Alive/

### ISSUE THREAD

**Issue by andreycruz16** [sw3103/movemouse#27]
Keep Citrix Workspace Alive without using mouse movement
I tried using the Activate Application, but the citrix workspace session still ends after x amount of time.

**Comment by sw3103** [comment]
Once you have brought the Citrix Workspace window to the foreground, do you perform and more Actions?

**Comment by overunityx** [comment]
I use citrix workspace (2022) and this does keep the session (and remote workstation) alive, when citrix window is in foreground.
There could be other factors like Citrix Admin policy requires specific activity on key applications, or sessions are forced to be refreshed after a time.
