### ISSUE TITLE
New sleep action is great, but I'd love it if it had a random time interval, such as the one under Behavior.

### ISSUE THREAD

**Issue by Pun-Ted** [sw3103/movemouse#3]
Currently, with the Sleep action, you can only set it to trigger a specific delay, such as 5 seconds. I'd like to see it have the same time settings as the time under Behavior, where you can set it to between x and X seconds. 

Thanks in advance, 
Pun-Ted

P.S. This program is GREAT.

**Comment by sw3103** [comment]
Hi,

If you're using Windows 10 and able to download the 4.x version from the Microsoft Store, you will see this functionality.

If not, it is still possible to do this if you'e happy to dip into a bit of scripting to edit the underlying XML file.
