### ISSUE TITLE
[Feature Request] - Save current active window / re-activate previously active window

### ISSUE THREAD

**Issue by egravel** [sw3103/movemouse#32]
Would it be possible to have an action such as "re-activate previously used window"?  Or the ability to save the currently used window and then reference it in the "activate" action?

I'm often on Zoom calls or watching training videos from my laptop and need to keep my Virtual Desktop (Citrix) active.  Currently, I have an action sequence that activate the VD window and moves the mouse which prevents it from disconnecting after being idle for X minutes.  But then I have to click back to where I was to continue to work, ie Zoom meeting or training site.

**Comment by sw3103** [comment]
I have just added a scenario for this, along with the supporting scripts. Please test and let me know how you get on.

https://github.com/sw3103/movemouse/wiki/Scenarios#reactivate-previous-active-window-on-pausestop
