### ISSUE TITLE
Bitdefender Total identifies mousemove.exe as a virus

### ISSUE THREAD

**Issue by Rxich** [sw3103/movemouse#34]
Advanced Threat Defense

Application Move Mouse.exe has been detected as potentially malicious and was blocked.
Application path: C:\Users\Dadz\Downloads\Move Mouse.exe
Command line parameters: "C:\Users\Dadz\Downloads\Move Mouse.exe" 
Detection ID: SuspiciousBehavior.B56F6B4A06045270

**Comment by sw3103** [comment]
There's not anything I can or will do about this. If an external virus program sees something in Move Mouse that is potentially malicious, it's your decision whether you use it or not.

The code is here for all to see and scrutinise.
