### ISSUE TITLE
Notification pop-up when Pause and Resume

### ISSUE THREAD

**Issue by AnaranBluto** [sw3103/movemouse#35]
On Windows 10, a Notification pop-up appears whenever the Action Pauses or Resumes from inactivity.  This had not happened before but started today.  I could not find the configuration property to disable notifications.

**Comment by becks0815** [comment]
I came to say the same. This is a total new bahaviour and I want to know how to stop the program from bombarding with messages during runtime.

**Comment by thunderpants** [comment]
I didn't notice anything ,not sure what that's about ,working fine here. 
Win21H2 fully updated.

**Comment by sw3103** [comment]
This was a new feature introduced in 4.15.0.

https://twitter.com/movemouse/status/1579095656144437251

Update to 4.15.1 where this has now been disabled by default.

https://github.com/sw3103/movemouse/releases/tag/v4.15.1
