### ISSUE TITLE
Movemouse staying idle after session lock/unlock

### ISSUE THREAD

**Issue by itztariq** [sw3103/movemouse#38]
I have come across this issue which I don't think was the case in the past, where the application goes into Idle after a screen/session-lock. The option of "continue performing actions when locked" is (and was in the past) disabled. However when window session is locked, movemouse is in active state but after unlock it goes to idle and remains idle requiring manual re-activation. So if I have locked say 4x times I have to activate it 4x time again which as I said wasn't the case in the past.

I have seen an article on troubleshooting going to idle but don't think that's same as going to idle as result of session lock. So would be great if this can be looked into please. Thanks.

**Comment by sw3103** [comment]
I have just released 4.16.0 that should resolve this issue. Please test and let me know if it's working for you.

https://github.com/sw3103/movemouse/releases/tag/v4.16.0

**Comment by itztariq** [comment]
Looks like that bit is resolved as I don't see it going idle after unlock.

However there is one odd thing I've noticed and not sure it is just me or is this version actually missing that bit - The System Tray Icon, it doesn't show that little yellow shade anymore when MM is active. Previously when MM is idle, the icon would have standard white color at the bottom centre part but that would turn yellow when MM was active, indicating that its running. It just doesn't seem to change that colour anymore ?

Regards,
Tariq
________________________________

**Comment by sw3103** [comment]
You have an eagle eye. I should use you as my QA tester for each release 😃 

I have temporarily disabled these icons as I just wasn't happy with how they looked. They will be making a return in the next release once I create better scaling versions.

**Comment by itztariq** [comment]
Ah I see, well at least for me I can say that this indicator proves more important then the issue you fixed and here is why - I run MM with 'hide move mouse window' which means the only way to know if its running or not is that little yellow shade.

In earlier issue, I was able to assess whether its stopped so would just double click to know its back again. Now I wouldn't know that at all unless I open the main App window, hope that make sense.

But thanks for confirming, glad its not off the radar. Will wait for next release.

And yes, I am sometime annoyingly into details, although don't think my colleagues like it very much ... for obvious reasons 🙂 But happy to report anything odd that I notice down the line. Cheers.
________________________________

**Comment by sw3103** [comment]
https://github.com/sw3103/movemouse/releases/tag/v4.16.1
