### ISSUE TITLE
schedule does not activate the next morning

### ISSUE THREAD

**Issue by lonelydrone** [sw3103/movemouse#39]
move mouse is in the tray however it does not seem active as my screen locks. I exit/end the program and restart and all is fine the schedule ends at the time specified however next day does not activate at the start time specified. is mouse move dependent on other tasks or scheduler that I may have disabled perhaps? TY!

**Comment by msackley5** [comment]
Same thing happens to me.  Basically is not functioning at all.  Have to remember to turn it on every day.

**Comment by renovatio118** [comment]
Same issue to me. Troubleshooting doesn't include any solutions about non-working scheduler. I've noticed that when time arrives, program stops but after computer goes to lock screen, it won't wake the screen again according to start schedule.

**Comment by sw3103** [comment]
There may not be anything in the guide specific to schedules, but it does show how to enable the logs that I will need to help troubleshoot.

**Comment by sw3103** [comment]
I tested Move Mouse throughout the night with two schedules to continuously stop/start it, and it seems to be working fine. I have also tested locking and putting the machine into hibernation and the schedules continue to work.

Without the logs and Settings.xml files I am unable to troubleshoot this further.

**Comment by renovatio118** [comment]
@sw3103
I believe the problem exists only if you download the "Windows Store" version. After downloading the GitHub version, seems ok now at first glance but i'll test further and i'll let you know if problem persists with logs and settings files.

**Comment by sw3103** [comment]
@renovatio118 the version I performed my testing with was the Microsoft Store version. It's the exact same version as what is published to GitHub, other than minor changes for some folder paths.

**Comment by renovatio118** [comment]
@sw3103 to me version from Microsoft Store is 4.15.1 and GitHub version is 4.16.1
I notice that taskbar icon has differences in appearence when it's active or idle. In my first tests GitHub version returns online (green light) when scedule time arrives to start but microsoft store version doesn't.

**Comment by sw3103** [comment]
@renovatio118 can this be closed now or do you still need help?

**Comment by lonelydrone** [comment]
All set. I fiddled around with screen lock timers and the problem went away. not exactly sure what I did, however.
