### ISSUE TITLE
mouse not moving

### ISSUE THREAD

**Issue by oyztein** [sw3103/movemouse#4]
Hey
Downloaded the latest version from Windows Store.
I add move mouse action but it doesnt move the mouse when testing or waiting for it to activate.
I have Windows 10 Pro N with latest updates.

**Comment by handynotiz** [comment]
Is there any start argument for a batch file?

**Comment by sw3103** [comment]
Yes - there are two supported arguments for the 3.x version:

Change the default working directory for the "Move Mouse.xml" file (to a home drive, USB drive, etc.).
`/WorkingDirectory:"C:\Some Path"`

Enable the tool window style.
`/EnableToolWindowStyle`
