### ISSUE TITLE
Tray icons status indicator

### ISSUE THREAD

**Issue by warthurton** [sw3103/movemouse#41]
Release 4.16.0
has commented out the tray icon status indicator.

https://github.com/sw3103/movemouse/commit/6dbcebf6400f16eee6fdf71182bdae6cc47753b7?diff=split#diff-8458cb4d91c515bfa1aa1df0f33912af576a98124f2e0946c877c01e0f18e128R310

Can this be restored?

**Comment by warthurton** [comment]
Thanks!  They are much easier to see the status now too!  PayPal tip incoming. I've been using the app for over 5 years. Since before the uwp? version!

**Comment by Taomyn** [comment]
@sw3103 Can we have an option to switch back? Hate the new icon with the coloured background as the "mouse" gets lost in the image. I've never had a problem with the small indicator.

**Comment by sw3103** [comment]
I will be switching back to better quality orbs in the next release.
