### ISSUE TITLE
Move mouse indefinetely

### ISSUE THREAD

**Issue by DhaWae** [sw3103/movemouse#42]
I want to move the mouse forever in one direction, how is this accomplished do i need to change any code

**Comment by sw3103** [comment]
If that is all you need, then maybe a script would be more suitable? Take a look at the PowerShell code here:

https://github.com/sw3103/movemouse/wiki/PowerShell-Snippets#silently-move-mouse-cursor

Edit the `[System.Drawing.Point]::New(0, 0)` in the loop to alter the direction the cursor will move, for example:

`[System.Drawing.Point]::New(1, 0)`
`[System.Drawing.Point]::New(0, 1)`
`[System.Drawing.Point]::New(-1, 1)`

You may also want to edit `Start-Sleep -Seconds 30` to control the speed at which the cursor move, or maybe remove it altogether.

**Comment by DhaWae** [comment]
Hello, I got it working. Thanks alot!
