### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by versavius** [sw3103/movemouse#43]
Are there any plans to release this app on Linux, the Windows version is excellent.

Thanks

**Comment by sw3103** [comment]
Not possible I'm afraid. It would require a complete rewrite, and none of the low-level APIs that are used to simulate activity are available on Linux.

If you were looking for simple functionality you could maybe look at something like this.

https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html
