### ISSUE TITLE
Tracking XY location not working properly

### ISSUE THREAD

**Issue by andychou** [sw3103/movemouse#44]
When I try to use this feature, it just oscillates between 3.0 and 2.9 seconds without moving the mouse. Never gets down to 0.

**Comment by sw3103** [comment]
It sounds as though you may have something else disrupting your idle time which is causing Move Mouse to think there is user activity.

Take a look at the script here to see if anything is resetting your idle time.

https://github.com/sw3103/movemouse/wiki/Troubleshooting#idle-time

**Comment by sw3103** [comment]
Did you use the script to see if anything else was resetting your idle time?
