### ISSUE TITLE
Bluetooth mouse "sleep mode"

### ISSUE THREAD

**Issue by Levde** [sw3103/movemouse#45]
Hi, your program does a lot of things, many of which I do not grasp. I was looking for a program that would tell my computer "this mouse is in use", because it goes into sleep mode if I don't use it for 30 seconds. 
My mouse is called a BT3.0 or BT5.2 mouse, on the internet it shows up as a Microsoft branded mouse. I guess sleep mode is supposed to save the battery, but it's super annoying, because to wake it up, it requires a click, and that click will activate any button that is under the cursor. 
I was hoping that Movemouse would tell the computer that the mouse is moving, and therefore don't go into sleep mode. Unfortunately, even when movemouse is active (I can see the cursor doing a little dance), the BT3.0 will go into sleep mode. 
Of course, I do not know whether the fault is in settings, or my version of windows, or you didn't design the program to do that. If you would care to try, I can be recruited for assistance. 
I have windows OS build 19044.2728
Thank you for your interest.

**Comment by sw3103** [comment]
Hi,

To start with - Move Mouse should be keeping your session alive, providing you have configured the correct Actions to do so.

I always suggest reading through the Troubleshooting section on the Wiki as this will help you through a lot of the most common issues that have been reported over the years.

https://github.com/sw3103/movemouse/wiki/Troubleshooting

When Move Mouse executes your Actions, this isn't going to wake your physical mouse, so don't be concerned that your devices aren't activated.
