### ISSUE TITLE
Feature Request - Minimize to Taskbar

### ISSUE THREAD

**Issue by mysticorient** [sw3103/movemouse#48]
I love this little app!  The problem I've found is the big "mouse" image remains on my desktop. I would like to be able to minimize it to the taskbar so if I share my screen, it's not on display for everyone to see.  Is this possible?  Is there already a way to minimize the application?  Thanks

**Comment by sw3103** [comment]
There are various Appearance options that can help you here.

https://github.com/sw3103/movemouse/wiki#appearance

I would recommend enabling the "Minimise when not running" option so that Move Mouse will automatically hide when in use.
