### ISSUE TITLE
Feature Request - Variability in scheduled start/stop times

### ISSUE THREAD

**Issue by moistpope** [sw3103/movemouse#49]
Basically title. Seems suspicious that you show online at the same time every morning - could there be an option to randomly stray from the scheduled time by +/- x minutes?

**Comment by telorand** [comment]
Couldn't you solve that problem by having different schedules? You could do one for each day of the week or even one for each day of the month.

**Comment by sw3103** [comment]
Move Mouse uses a Cron scheduler, which doesn't support randomisation out of the box.

You could workaround this by adding a Sleep Action with a random duration at the very start:

https://github.com/sw3103/movemouse/wiki#sleep

**Comment by sw3103** [comment]
New [4.17.0](https://github.com/sw3103/movemouse/releases/tag/v4.17.0) release which offers a random delay on schedules.

![image](https://github.com/sw3103/movemouse/assets/29467423/2050f4a5-872b-4209-a372-4270cc929bab)

Please test and see if this meets your requirements.

**Comment by sw3103** [comment]
@moistpope did you have a chance to test version 4.14.0?

**Comment by moistpope** [comment]
I did - it’s worked great 👍
