### ISSUE TITLE
Feature Request: Save App Settings in the Same Folder

### ISSUE THREAD

**Issue by ToggoStar** [sw3103/movemouse#50]
Hello sw3103,

first off: Thanks a bunch for this awesome app! I've been using it for quite a while now and it perfectly fits my needs <3!

I do have one tiny request though: Is there anyway to add a toggle making the program save the settings in the same folder as the executable? That would make the program truly portable!

Cheers,
ToggoStar

**Comment by sw3103** [comment]
Hi @ToggoStar,

I think this is what you're after:

https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)#workingdirectory

Let me know if this satisfies your requirements.

**Comment by ToggoStar** [comment]
> Hi @ToggoStar,
> 
> I think this is what you're after:
> 
> https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)#workingdirectory
> 
> Let me know if this satisfies your requirements.

Perfect, thank you!
