### ISSUE TITLE
Does not work after a hibernate. 

### ISSUE THREAD

**Issue by Islamimad96** [sw3103/movemouse#56]
After a normal hibernate (win 10) it doesn't function at all I've tried everything in the settings but no luck.

**Comment by sw3103** [comment]
Please follow the Troubleshooting guide to see if that helps isolate the issue.

https://github.com/sw3103/movemouse/wiki/Troubleshooting

**Comment by sudo-mk-sandwich** [comment]
I've built a workaround for that:
Create batch-file with following commands:
taskkill /IM "Move Mouse.exe"
start "" "Path to Move Mouse.exe"

Then create a task in Windows Task Scheduler, to run this batch at trigger workstation unlock. At settings tab choose quit after 1 hour and allow new instances parallel.

**Comment by sw3103** [comment]
@Islamimad96 did the logs reveal anything?

**Comment by sw3103** [comment]
Glad you found a solution, even if I don't understand it!
