### ISSUE TITLE
Microsoft Defender SmartScreen issue

### ISSUE THREAD

**Issue by PatUMW** [sw3103/movemouse#58]
Microsoft Defender SmartScreen prevent Move Mouse.exe from executing in Win 10 Pro because of "Unknown publisher". Screenshot below in Polish language.
According to this [stack's advice](https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro) may you try to [submit your app for malware analysis to Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission)?

![image](https://github.com/sw3103/movemouse/assets/110469155/64d614af-c0d9-4206-9c16-778539315d8a)

**Comment by sw3103** [comment]
If you use the Microsoft Store version you will avoid this.
