### ISSUE TITLE
Import Export of settings

### ISSUE THREAD

**Issue by Real-Ryououki** [sw3103/movemouse#61]
Hello, could we please get an option to import/export all the settings in Move Mouse?

If not, where are these settings stored?

Thank you.

**Comment by sw3103** [comment]
Hi,

Depending on where you downloaded Move Mouse from will depend on where the Settings.xml file will be stored:

https://github.com/sw3103/movemouse/wiki/File-Locations

If you are looking to keep Move Mouse settings in sync on multiple machines, you might also consider the WorkingDirectory CLI option:

https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)#workingdirectory
