### ISSUE TITLE
Hide the annoying popup in the top left corner.

### ISSUE THREAD

**Issue by kamilwlf** [sw3103/movemouse#65]
<img width="123" alt="image" src="https://github.com/sw3103/movemouse/assets/7765963/f6f5deca-d00f-4bca-8c13-095d29d44d6d">
Hide the annoying popup in the top left corner.

**Comment by sw3103** [comment]
Resolved in the 4.17.0 pre-release.

https://github.com/sw3103/movemouse/releases/tag/v4.17.0
