### ISSUE TITLE
Is it possible to export settings?

### ISSUE THREAD

**Issue by airbagi** [sw3103/movemouse#67]
Hi, 
Where the settings of the program are stored? In order I can export them and import to another PC?

Many thanks!

**Comment by sw3103** [comment]
Hi,

You can find the relevant paths here:

https://github.com/sw3103/movemouse/wiki/File-Locations

Another option if you are using the GitHub version and have the two machines connected using the same network/cloud drive is to use the CLI option to share settings between multiple machines.

https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)#workingdirectory
