### ISSUE TITLE
Range of mouse movement distance and probability

### ISSUE THREAD

**Issue by saper3333** [sw3103/movemouse#69]
I think we need to add a range of cursor movement distance, which will be randomly selected from the back range each time.
![2024-04-26_09-59-43](https://github.com/sw3103/movemouse/assets/40059860/c74dcb80-862e-4665-8198-6cc67026ba66)
As well as the probability of triggering an action as a percentage, for example, 100% is triggered every time.
![2024-04-26_10-09-09](https://github.com/sw3103/movemouse/assets/40059860/16ab3b29-fbeb-4c74-bf79-c80297f0d794)

**Comment by sw3103** [comment]
Take a look at the 4.18.0 pre-release that I published a couple of days ago.

https://github.com/sw3103/movemouse/releases/tag/v4.18.0

**Comment by saper3333** [comment]
> Take a look at the 4.18.0 pre-release that I published a couple of days ago.
> 
> https://github.com/sw3103/movemouse/releases/tag/v4.18.0

Great. Thanks a lot. It would be great to see another function, “Probability”, which is responsible for the probability of the action triggering, and is indicated in the range of 1% - 100%
