### ISSUE TITLE
"Automatically Resume" is missing

### ISSUE THREAD

**Issue by pviolette92** [sw3103/movemouse#70]
Running 4.18.2. Just noticed the option to enable auto resume is gone
<img width="521" alt="Screenshot 2024-06-03 101412" src="https://github.com/sw3103/movemouse/assets/42838611/0fc1460c-6843-4e93-af04-7a696382d4fa">

**Comment by sw3103** [comment]
You need to enable the "Automatically stop..." option for that to become available.

**Comment by pviolette92** [comment]
There we go. Thank you
