### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by imessyou** [sw3103/movemouse#71]
[Behaviour]-[Repeat actions 1 second]

Can only be filled in for more than 1 second,
If it could be changed to 0.1 seconds, that would be even better

I tried to input 0.1 seconds, it can input, but the program still runs with an interval of 1 second

**Comment by ysaykin** [comment]
Would it be possible to add an export and import option for settings? My settings get constantly erased for some reason and having this manual option would go a long way to making the app better. Also someone can have different settings for different situations that they might want to load manually.

**Comment by sw3103** [comment]
> [Behaviour]-[Repeat actions 1 second]
> 
> Can only be filled in for more than 1 second, If it could be changed to 0.1 seconds, that would be even better
> 
> I tried to input 0.1 seconds, it can input, but the program still runs with an interval of 1 second

That is quite an aggressive repeat interval and may cause issues in the interface.

If you can let me know which actions you are performing it may make more sense to use a PowerShell script which I can assist you with.

**Comment by sw3103** [comment]
> Would it be possible to add an export and import option for settings? My settings get constantly erased for some reason and having this manual option would go a long way to making the app better. Also someone can have different settings for different situations that they might want to load manually.

Your settings are stored here:

https://github.com/sw3103/movemouse/wiki/File-Locations

If you are using the GitHub version you can also use the CLI to either work with multiple Settings.xml files or share them across different workstations.

https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)

If you require any more assistance please open a new issue rather than replying to an existing one.

**Comment by W-illi4m** [comment]
is it possible to add a feature to type text?
e.g.
1. position cursor
2. type text "my text"
3. position cusror
4. click

**Comment by sw3103** [comment]
> is it possible to add a feature to type text? e.g.
> 
> 1. position cursor
> 2. type text "my text"
> 3. position cusror
> 4. click

Moved to new issue.
