### ISSUE TITLE
[FEATURE REQUEST] settings location and maintenance

### ISSUE THREAD

**Issue by rupacheco** [sw3103/movemouse#72]
Where are the settings saved, is there any way to migrate them between machines?
In case we need to fully erase the application and it's settings how should we proceed?
Can this use case be addressed please?

**Comment by sw3103** [comment]
Settings can be located here:

https://github.com/sw3103/movemouse/wiki/File-Locations

If you are using the GitHub version you can also use the CLI to specify your own path:

https://github.com/sw3103/movemouse/wiki/Command-Line-Interface-(CLI)
