### ISSUE TITLE
Interval isn't working

### ISSUE THREAD

**Issue by royda** [sw3103/movemouse#73]
1) In the Behaviour section: I set the app to "Repeat actions" every 90 seconds (see pic).
2) In the Actions section: I have a Position Mouse Cursor with an Interval which is Throttled to 2 (see pic).

Expectation: This should cause the app to move the mouse cursor to the given position twice and then stop. It does not. It keeps repeating endlessly.

This is either a bug or I'm completely misunderstanding the expected behaviour. Otherwise, great app! Thank you.

![movemouse1](https://github.com/user-attachments/assets/de4c1946-25b9-4f99-bf38-8dd4e7cbc201)
![movemouse2](https://github.com/user-attachments/assets/da5a7aaa-490a-4e96-99fd-713c298b305e)

**Comment by sw3103** [comment]
Your expectation is correct. This looks like a bug.

**Comment by sw3103** [comment]
@royda please test the 4.18.3 release and confirm it resolves this issue.

https://github.com/sw3103/movemouse/releases/tag/v4.18.3

**Comment by royda** [comment]
@sw3103 I can confirm that it's fixed. Thanks for your hard work!

**Comment by royda** [comment]
Fixed
