### ISSUE TITLE
Move Mouse has disappears

### ISSUE THREAD

**Issue by W-illi4m** [sw3103/movemouse#75]
Hi Steve,
I don't know what parameters I have changed but Move Mouse is still running in Windows processes (in task manager) but I can't make the UI visible again  _to start it_ or _to change parameters_. 
Alt+tab do not list Move Mouse
Any Idea?

**Comment by sw3103** [comment]
If you kill it and re-launch, do you momentarily see the system tray icon?

https://github.com/sw3103/movemouse/wiki#hide-system-tray-icon

**Comment by W-illi4m** [comment]
Yes ! that's help. Thanks.

Le lun. 7 oct. 2024 à 14:17, Steve Williams ***@***.***> a
écrit :
