### ISSUE TITLE
Why can't it be moved?

### ISSUE THREAD

**Issue by fbauer-kunbus** [sw3103/movemouse#81]
Am I missing something or is this nice little tool always glued to the center of the screen? Why is this? Why can't it be moved to any place I like?

**Comment by sw3103** [comment]
You can move it by dragging the main form. You will need to hover the mouse pointer near the outside of the circle and watch the cursor change from a hand to a directional indicator.

**Comment by fbauer-kunbus** [comment]
> You can move it by dragging the main form. You will need to hover the mouse pointer near the outside of the circle and watch the cursor change from a hand to a directional indicator.

Sure! Thank you ... sorry for not having realized this ...
