### ISSUE TITLE
move mouse crashing

### ISSUE THREAD

**Issue by jenjen909** [sw3103/movemouse#9]
hi, i have recently tried to run move mouse 3.5 on windows 7, after running it. i can see the icon on task bar, but i can't start the app or open the app. whenever i tried to start or open it, it crashes and close automatically.

**Comment by sw3103** [comment]
Hi @jenjen909,

Are you able to run the previous version?

https://github.com/sw3103/movemouse/releases/tag/v3.4.1

**Comment by jenjen909** [comment]
hi there, the older version actually works..! thanks

**Comment by sw3103** [comment]
Version 3.6.0 now available without KryptonWinFormControls UI components.
